### ISSUE TITLE
Possible inconsistency between paper and repository

### ISSUE THREAD

**Issue by anika-ilieva** [youngbin-ro/Multi2OIE#4]
I recognised a difference between your code and the Paper [Multi^2OIE: Multilingual Open Information Extraction Based on Multi-Head Attention with BERT](https://arxiv.org/abs/2009.08128).
While the paper uses key and value (both masked BERT hidden states) and an unmasked query (BERT hidden state) as inputs for the MultiHeadAttention Blocks, your code uses the same query and value (both BERT hidden states) and a key (masked BERT hidden state).

Paper:
key = value = bert_hidden[masked]
query = bert_hidden

Your Repository:
query = value = bert_hidden
key = bert_hidden[masked]

Maybe I understood something wrong, but why did you change this part of the architecture?

**Comment by youngbin-ro** [comment]
Hi, I think you probably misunderstood the repository part.
Perhaps the part below confuses you.
https://github.com/youngbin-ro/Multi2OIE/blob/3964e9c68aa9721800791de02d1ec7bdcb5fe3a7/model.py#L150
In the above code, the first `bert_hidden` means query, and the second `bert_hidden` means key and value.
The last `predicate_mask` is used to mask the second `bert_hidden`(key and value).
As a result, the above line behaves the same way as described in the paper you mentioned.
```
query = bert_hidden
key = value = bert_hidden[masked]
```
Additionally, in most self-attention modules, key and value are computed from the same feature. It is rarely used in a way that the query and the value are the same and only the key is different.

If your question is resolved, please close the issue, and feel free to ask any additional questions.
