### ISSUE TITLE
Having trouble replicating results with file structuring

### ISSUE THREAD

**Issue by darasimia** [youngbin-ro/Multi2OIE#5]
I have noticed some slight inconsistencies when trying to replicate the results of this model starting from testing. When the general reader script is run it takes in "openie4_test.txt" but this file does not seem to exist in the repository. Do you know why this is?

**Comment by youngbin-ro** [comment]
Hi!
In our study, we do not use the `openie4_test.txt` file as a test set.
I think the below line confuses you.
https://github.com/youngbin-ro/Multi2OIE/blob/4a73a3c37412541748859a6c70bcc1847897bb57/evaluate/generalReader.py#L35-L43
However, this code is just copied code as we borrowed the evaluation code of [Span_OIE](https://github.com/zhanjunlang/Span_OIE).
If you want to perform evaluation on the `Re_OIE2016` and `Carb-test` data presented as evaluation sets by our study, refer to the [test.py](https://github.com/youngbin-ro/Multi2OIE/blob/master/test.py) file.

If your question is resolved, please close the issue, and feel free to ask any additional questions.
