### ISSUE TITLE
Format of data for test.py

### ISSUE THREAD

**Issue by RuslanAbliazov** [youngbin-ro/Multi2OIE#6]
Thank you for your amazing work.
I have troubles in launching trained model for my dataset. I have dataset in .txt format, that I should to do to convert it to .pkl format properly?

**Comment by RuslanAbliazov** [comment]
To make it more clear: I want to receive a file that will need to be specified in --test_data_path in test.py. For example I tried to write 2 sentences from carb dataset in .txt line by line and then convert to .pkl using pickle package but model extracted nothin from the resulting file.

**Comment by youngbin-ro** [comment]
Hello, thank you for your interest in our research. For `--test_data_path` in `test.py`, you can specify the file `carb_test.pkl` in the folder `datasets (sample)`. I don't know how you converted the .txt file into a .pkl file, so I don't know how to advise you on your situation, but when I worked in my environment, the performance recorded on README.md is reproduced as it is when I evaluated on the file `carb_test.pkl`. If you have any other issues, please leave the details with the error log.

**Comment by RuslanAbliazov** [comment]
I find answer on my answer in [preprocess.py](https://github.com/youngbin-ro/Multi2OIE/blob/master/utils/preprocess.py) in function `preprocess_dev_input`.

Thanks for your response!
